apiVersion: apps/v1
kind: Deployment
metadata:
  name: shgp-backend-django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shgp-backend-django
  template:
    metadata:
      labels:
        app: shgp-backend-django
    spec:
      containers:
      - name: shgp-backend-django
        image: acrshgpdev1.azurecr.io/shgp:228
        #imagePullPolicy: Always
        ports:
        - containerPort: 8002

---

apiVersion: v1
kind: Service
metadata:
  name: shgp-backend-django-service
spec:
  selector:
    app: shgp-backend-django
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8002
  type: NodePort

