apiVersion: apps/v1
kind: Deployment
metadata:
  name: shgp-backend-django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shgp-backend-django
  template:
    metadata:
      labels:
        app: shgp-backend-django
    spec:
      containers:
      - name: shgp-backend-django
        image: acrshgpdev1.azurecr.io/shgp:226
        #imagePullPolicy: Always
        ports:
        - containerPort: 8002

---

apiVersion: v1
kind: Service
metadata:
  name: shgp-backend-django-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8002
  selector:
    app: shgp-backend-django