# Generated by Django 2.2.8 on 2020-01-06 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100, null=True)),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('creator', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
